### ISSUE TITLE
set evm version in config

### ISSUE THREAD

**Issue by bout3fiddy** [ApeWorX/ape-vyper#86]
### Overview

in ape-config.yaml, allow user to do:

```
vyper:
    evm_version: shanghai
    arbitrum:
         evm_version: paris
```

**Comment by antazoey** [comment]
the first part of this already should work:

```
vyper:
  evm_version: shanghai
```

let me know if it doesnt but it was added here: https://github.com/ApeWorX/ape-vyper/commit/b75ee5de0c2e8101f4aaf5bd3b1dc4ceb45d4869

the second part is a valid refactor request though, however it may look like:

```
vyper:
  ethereum:
    evm_version: shanghai
  arbitrum:
    evm_version: paris
```
